### ISSUE TITLE
Remove file name 

### ISSUE THREAD

**Issue by bachnxhedspi** [nzambello/react-csv-reader#14]
Hi @nzambello 

I wonder is there anyways I can remove the filename (move it back to "No file chosen") after handling and submit the data.

Btw, thank you for a great csv reading component.

**Comment by nzambello** [comment]
Hi @bachnxhedspi, you're welcome.

I tested on the demo on codesandbox (you can find the link in the README) and I did a reset by doing:
```js
document.querySelector('.csv-input').value = ''
```

The component doesn't have a prop or a public method to do so, then I think this is the best solution to your problem at the moment. I can't find a react-er way, I'm sorry.

Another solution could be - if the component is in a form - to reset the entire form.

**Comment by bachnxhedspi** [comment]
@nzambello Thank you for your quick response. 

I will give it a try and let you know if any problems arises.
