### ISSUE TITLE
How can I trigger click event without jQuery?

### ISSUE THREAD

**Issue by hhphuc12** [nzambello/react-csv-reader#15]
I have `CSVReader` component and a button. I want when I press the button, input of `CSVReader` will be clicked, so my code (use jQuery) is:
`<button onClick={() => $('.csv-input').click()}>Trigger</button>`

If I use `ref` property instead of jQuery, the code is:
`<CSVReader ... ref={ref => this.csvInput = ref}/>`
`<button onClick={() => this.csvInput.click()}>Trigger</button>`
But `ref` is not available, please add it to your module. Thank you so much!

**Comment by nzambello** [comment]
I'll check this as soon as possible

**Comment by nzambello** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click
