### ISSUE TITLE
how can I upload same edited file?

### ISSUE THREAD

**Issue by nwkk** [nzambello/react-csv-reader#17]
after I upload csv file, then I edit the same file with same name but different content and upload again. The handleChange method doesn't trigger. is  there any way to upload same edited file? Thank you.

**Comment by nzambello** [comment]
I'm testing some way.
As a user, you can click on the button and then Cancel on the system modal where you could select a file. In this way, the input element is reset.
You could try to implement something like this if your use case is different.

**Comment by yasithph** [comment]
I got this to work by wrapping the reader inside a div, giving it an unique id and having a clear button. 

This is how it is wrapped in a div.
`
<div key={this.state.theInputKey || ''} >
                  <CSVReader
                    cssClass="react-csv-input inputfile"
                    inputId="file-upload"
                    onFileLoaded={this.handleForce}
                    onError={this.handleUploadError}
                  />
  </div>
`
This is how I change the state when clear button is pressed.

`
cancelUploadedFile() {
    const randomString = Math.random().toString(36);
    this.setState({
      theInputKey: randomString,
    });
  }
`

This re-renders the csv reader hence resets the input element.
