### ISSUE TITLE
Can I change default file extension ?

### ISSUE THREAD

**Issue by cutejjc** [nzambello/react-csv-reader#19]

**Comment by nzambello** [comment]
How would you change it? It's built to read csv files, what kind of files do you want to handle?

**Comment by cutejjc** [comment]
I want to read a custom text file with file extension .lst or .dat.(the
contents are csv format). But evertime I open the file browser of the
component, I have to change it. I just want to set the default file
extension on the component code easily.
Thanks.



2019년 7월 29일 (월) 오후 11:53, Nicola Zambello <notifications@github.com>님이 작성:

**Comment by nzambello** [comment]
There is a `accept` prop you can pass to the component.
I'm adding it in the README

**Comment by cutejjc** [comment]
Thank you!

2020년 3월 14일 (토) 오후 7:33, Nicola Zambello <notifications@github.com>님이 작성:
