### ISSUE TITLE
Css for "choose file" button

### ISSUE THREAD

**Issue by digholesnehal** [nzambello/react-csv-reader#23]
I tried applying css for button by using "cssClass", "cssInputClass" and "inputStyle" but it was changing the style of the file name but not of Button.

**Comment by ricotheque** [comment]
This component uses the file input element, which are [notoriously hard to style](https://stackoverflow.com/questions/572768/styling-an-input-type-file-button).

Your best bet is hiding the input itself, [replacing it with another element that you can actually style](https://stackoverflow.com/a/25825731).

**Comment by andlon10** [comment]
@ricotheque is correct, what I ended up doing in my case, was moving the CSV reader input into a Material UI Upload button, then, using the inputStyle prop I did something like this:
`{ opacity: 0, width: '170px', marginLeft: '-170px' }`

This way the invisible input sits right on top of the button and allows you to use a (much) better style. It is a small hack, you may need to add some extra CSS bits (like the pointer) but it should work as expected.
