### ISSUE TITLE
is there a way to get csv file name in onload event  ?

### ISSUE THREAD

**Issue by ntedgi** [nzambello/react-csv-reader#25]
on load returns csv data without the file meta data

**Comment by nzambello** [comment]
Hi @ntedgi.
It's not implemented anything for this, yet.

In this line of code you can see where I get filename:
https://github.com/nzambello/react-csv-reader/blob/master/src/index.js#L20

We could add a method which, as a callback, provides the name of the file it's parsing.

**Comment by ntedgi** [comment]
great i saw that you pass the file name also as a parameter to the **onFileLoaded** callback  
here :
[https://github.com/nzambello/react-csv-reader/blob/acbcea4863e42bb8f42ea8716b13bac2bcf4de68/src/index.js#L30](url)

i think it will be great if you change the basic example usage :

  <CSVReader onFileLoaded={(data,fileName) => console.log(data)} />

thanks

**Comment by nzambello** [comment]
Oh right! I forgot that.
I've just updated README and the demo on CodeSandBox.

Thank you!
