### ISSUE TITLE
Filezie upload

### ISSUE THREAD

**Issue by rasyid46** [nzambello/react-csv-reader#27]
whether this library can detect file size ?
thank you

**Comment by nzambello** [comment]
While adding TypeScript in the project, I made a change in the callback return type: now I return the data and an object with file infos: name, size and type.
See #34 .

For reference: returned value for size property is documented here https://developer.mozilla.org/en-US/docs/Web/API/File/size

**Comment by nzambello** [comment]
Released in v3.0.0.
See https://github.com/nzambello/react-csv-reader#onfileloaded
