### ISSUE TITLE
Where to input a file?

### ISSUE THREAD

**Issue by redefinered** [nzambello/react-csv-reader#28]
Not sure why the doc does not indicate where to input the file.

**Comment by nzambello** [comment]
Hi, this React component renders a <input type="file" />.
As a user, you can interact with it uploading a csv file.

I don't know if I understood correctly your question. Have I answered you?

**Comment by redefinered** [comment]
It looks like you did but I already forgot how I was implementing this and why drove me to create this issue. Closing it now. Thanks!
