### ISSUE TITLE
Chrome showing error Warning: `value` prop on `input` should not be null

### ISSUE THREAD

**Issue by anil3a** [nzambello/react-csv-reader#29]
Hi, guys, i tried to see if there is any issue that has been created or google it but couldn't solve it.

Every time i load this CSV component I get following error in my chrome. 

Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

Not sure how will it solve, but i guess if you have a value attribute with empty string instead of null then this error might go away.

**Comment by nzambello** [comment]
Does it happen to you with the demo, too? https://codesandbox.io/s/react-csv-reader-vtull

Could you explain me how you're handling the component?
I'm not using `value` attribute as it's not needed to load a file, the thing here is the callback to get the loaded file.

**Comment by anil3a** [comment]
Yap, your demo didn't have any error that i can see.

Let me show my view file and its rendered view with error console in the image if this helps. 

![image](https://user-images.githubusercontent.com/2561627/75834952-b1489380-5e11-11ea-9856-941caa7ba6c5.png)

My package.json has this as well if this helps:

```
"dependencies": {
    "react": "^16.8.6",
    "react-csv-reader": "^2.0.2",
    "react-dom": "^16.8.6",
    "react-router-dom": "^5.0.0"
  },
```

**Comment by nzambello** [comment]
Are you sure it depend on this component? The logs are pointing to line 257.

**Comment by anil3a** [comment]
I am so sorry, ;( how embarrassing is this. It came from another field i had there in that line. Your plugin is amazing thank you :)
