### ISSUE TITLE
Casting fields as number

### ISSUE THREAD

**Issue by caio-davi** [nzambello/react-csv-reader#36]
Hi, 

All the fields are being cast. So, values like '02310' are imported as '2310'. 
I'm not sure if this is the desired behavior, but I need to keep the original value.
Is there a way to do this?

Thank you,

**Comment by nzambello** [comment]
Hi, yes, there is!
This isn't my component's fault, it's PapaParse configuration stuff, as explained [here](https://github.com/nzambello/react-csv-reader#parameters).

In my example in the README the config object uses:

```js
{
  ...
  dynamicTyping: true,
}
```

and this make PapaParse to convert strings if the value can be a number or something else (I guess).
See docs [here](https://www.papaparse.com/docs#config).

So, if you're not using that configuration attribute, you should be fine, having only strings as they are.

Tell me if this helps you.

**Comment by caio-davi** [comment]
Yes, it help me a lot!

Thank you!
