### ISSUE TITLE
typescript definition are missing

### ISSUE THREAD

**Issue by apoorvmote** [nzambello/react-csv-reader#37]
I chose this library over others because majority of the code is written in typescript.
When I add this to my project it gives me error
```
Could not find a declaration file for module 'react-csv-reader'. '/home/apoorvmote/import-export/node_modules/react-csv-reader/dist/react-csv-reader.js' implicitly has an 'any' type.
  Try `npm install @types/react-csv-reader` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-csv-reader';`ts(7016)
```

**To recreate**
1. `npx create-react-app csv-test --use-npm --template typescript`
1. `npm i react-csv-reader`
1. In App.tsx just add this line `import CSVReader from 'react-csv-reader'`
then you get the error mentioned above.

**Comment by adammesa** [comment]
+1 Am also having this issue

**Comment by nzambello** [comment]
@apoorvmote @adammesa Fixed in v3.0.3 👍

**Comment by apoorvmote** [comment]
@nzambello I tested it and it works better now. 
If I had to be nitpicky then the `parserOption` is just any shape object. Which is better than before but it could be better.

**Comment by nzambello** [comment]
> @nzambello I tested it and it works better now.
> If I had to be nitpicky then the `parserOption` is just any shape object. Which is better than before but it could be better.

@apoorvmote Thank you for pointing it to me, I'm a newbie on typescript libraries.
Now typings provide full specifications for parserOptions, too.
Updated in v3.0.4

**Comment by adammesa** [comment]
@nzambello you, sir, are fast!

Thank you for all your hard work. (I am 3 days new to TypeScript and had no idea how to tackle this)

**Comment by apoorvmote** [comment]
Thanks for fixing again quickly. I am also relatively new to Typescript. I just have 1 year experience with Typescript. I am not 3 days into Typescript.

If anyone else wanted strictly typed parserOption then first install `npm i -D @types/papaparse` only the types as dev dependancy. Then on the tsx file `import { ParseConfig } from 'papaparse'`  this is type used for parserOption
