### ISSUE TITLE
npm run build failed to compile in create-react-app project

### ISSUE THREAD

**Issue by mergingseas** [nzambello/react-csv-reader#46]
**Describe the bug**
Getting failed to compile error when running npm run build.

error is failed to minify:
./node_modules/react-csv-reader/dist/react-csv-reader.js:1:1294

**To Reproduce**
1. run “npm run build” in create-react-app project

Used  node v13.11.0 npm v6.13.7

**Comment by longnguyenkms** [comment]
I have the same issue. Does anyone have a solution for this?

**Comment by nzambello** [comment]
I'm not succeeding in replicating it, either with TS or with ES templates of CRA.
Are you using something different from basic CRA env?

**Comment by nzambello** [comment]
Are you using the last version?
