### ISSUE TITLE
Camel case naming convention

### ISSUE THREAD

**Issue by kasugaicrow** [nzambello/react-csv-reader#49]
Hi,
is it possible to keep camel case naming convention (or any naming convention) during the parsing operation? My starting headers name are
```
username;email;firstName;lastName;enabled
```
but what I got is 
```js
{
  username: "username_test",
  email: "email_test",
  firstname: "firstname_test",
  lastname: "lastname_test",
  enabled: true
}
```
thanks.

**Comment by nzambello** [comment]
Hi, this is related to PapaParse configuration, not with this package.
https://www.papaparse.com/docs#config

Are you using the configuration on the README?
```js
  const papaparseOptions = {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: true,
    transformHeader: header =>
      header
        .toLowerCase()
        .replace(/\W/g, '_')
  }
```
If so, that's only an example and maybe I should specify this.
With these options for papaparse you'll get what you're reporting.
Remove or change `papaparseOptions` or its `transformHeader`

Let me know if this resolved your issue or if you resolved it in the meanwhlie.

**Comment by kasugaicrow** [comment]
Hi @nzambello, that's my bad actually. I only copied-pasted without paying attention so I don't think you should specify that in the README. Anyway it's resolved now, thank you!
