### ISSUE TITLE
add `inputRef` feature

### ISSUE THREAD

**Issue by gurrrung** [nzambello/react-csv-reader#61]
It should return a Ref to the input element.

**Comment by gurrrung** [comment]
Because https://www.javascriptstuff.com/use-refs-not-ids/

**Comment by gntsketches** [comment]
I second this request! It is recessary to reset the value of the input to upload more than once. (Try this on the demo page:
https://codesandbox.io/s/react-csv-reader-vtull ).

Great library though otherwise. Thank you!
