### ISSUE TITLE
npm run build failed to compile

### ISSUE THREAD

**Issue by danielbrito1987** [nzambello/react-csv-reader#70]
**Describe the bug**
I'm trying to compile my project for production, but the following error always occurs: 
Unexpected token: punc ()) [./node_modules/react-csv-reader/dist/react-csv-reader.js:1,1264][\js\app-rede.js:51124,1285]
I'm using webpack in my project. 

- node v12.22.1
- npm 7.14.0
- composer 2.0.12
- PHP ^7.0
- Laravel ^5.5

**Comment by nzambello** [comment]
Hi @danielbrito1987 👋 
May [this SO thread](https://stackoverflow.com/questions/65744545/webpack-5-unexpected-token-punc-after-import-axios) can help you? It doesn't seem a problem related to the library itself, so I suppose the environment and the build tooling should be debugged.
