### ISSUE TITLE
Problem with parserOptions --> delimiter

### ISSUE THREAD

**Issue by marcoscarvalho** [nzambello/react-csv-reader#8]
Hi,

When I pass something like this below, the delimiter ";" doesn't work.

```js
<CSVReader
      cssClass="react-csv-input"
      label="Select CSV with secret Death Star statistics"
      onFileLoaded={handleForce}
      parserOptions={{
        delimiter: ";" // Delimiter used
      }}
    />
```
Where I did my test: https://codesandbox.io/s/4rw9qwzzm7

Thanks

**Comment by nzambello** [comment]
Hi @marcoscarvalho what type of issue are you experiencing?
I had no trouble using a `.csv` file with a content like this:
```
header0;header1
content0a;content0b
content1a;content1b
content2a;content2b
```

**Comment by marcoscarvalho** [comment]
Sorry.
I open this issue because my file has ";" in the end of the lines.
But I understand now and Thanks.
