### ISSUE TITLE
React peer dependency version doesn't resolve for React 17 projects anymore

### ISSUE THREAD

**Issue by amrictor** [nzambello/react-csv-reader#95]
**Describe the bug**
Projects with React 17 fail to resolve peer dependencies.

**To Reproduce**
1. Install react-csv-reader to a project using React 17.
2. Observe error:
<img width="358" alt="Screen Shot 2022-04-27 at 11 27 25 AM" src="https://user-images.githubusercontent.com/26844212/165584757-3d0ec51a-81bc-4108-a6cb-4a3a8647a6c9.png">

**Expected behavior**

**Platform (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 

**Additional context**
This bug seems to originate at the most recent release in [this commit](https://github.com/nzambello/react-csv-reader/commit/a5de40d3b79813bf748ba03cde4e01a77052c384), not sure why the peer dependency version was changed.

**Comment by cp-Coder** [comment]
I am also facing the same issue in Firefox(Windows OS)

**Comment by OPADA-Eng** [comment]
Same here

**Comment by richardoptibrium** [comment]
Same. Could really do with a solution please.

**Comment by nzambello** [comment]
Released in v3.5.1
